platform:ios,'7.0'
target 'LLQDemo' do
  pod 'AFNetworking', '~> 2.6'
  pod 'TTTAttributedLabel', '~> 1.13.4'
  pod 'TPKeyboardAvoiding', '~> 1.3'
  pod 'FMDB', '~> 2.2'
  pod 'SDWebImage', '~> 3.7.5'
  pod 'RegexKitLite', '~> 4.0'
  pod 'ZBarSDK', '~> 1.3.1'
  pod 'MJRefresh', '~> 3.1.0'
end
